# frozen_string_literal: true

require "prism"

# Translates one verifiable-Ruby module into the Lean 4 definitions that the proofs are about.
module LeanTranslator
  Unsupported = Class.new(StandardError)

  # Lean source text helpers shared by the other parts.
  module Text
    PAIRS = { "(" => ")", "[" => "]", "{" => "}" }.freeze

    module_function

    def unsupported(node, message) = Unsupported.new("line #{node.location.start_line}: #{message}")

    def indent(lines) = lines.map { "  #{_1}" }

    def arm(head, lines) = lines.size == 1 ? ["#{head} => #{lines[0]}"] : ["#{head} =>", *indent(lines)]

    # Parenthesized unless it is one token or already one bracketed group.
    def atom(code) = code.match?(/\A([\w.]+|"[^"]*")\z/) || wrapped?(code) ? code : "(#{code})"

    # `if`, `fun` and `match` extend to the end of the line in Lean, so they need parens as an operand.
    def operand(code) = !wrapped?(code) && code.match?(/(\A|\s)(if|fun|match)\s/) ? "(#{code})" : code

    def wrapped?(code)
      return false unless PAIRS.key?(code[0])

      depth = 0
      code.each_char.with_index do |ch, i|
        depth += 1 if PAIRS.key?(ch)
        depth -= 1 if PAIRS.value?(ch)
        return i == code.size - 1 if depth.zero?
      end
      false
    end
  end
end

require_relative "lean_translator/types"
require_relative "lean_translator/schema"
require_relative "lean_translator/code"

module LeanTranslator
  module_function

  # Returns [module name, Lean source].
  def translate(source, path:)
    result = Prism.parse(source)
    raise Unsupported, result.errors.map(&:message).join("; ") if result.failure?

    mod = result.value.statements.body
    unless mod.size == 1 && mod[0].is_a?(Prism::ModuleNode) && mod[0].constant_path.is_a?(Prism::ConstantReadNode)
      raise Unsupported, "a file must hold exactly one top-level module"
    end

    mod = mod[0]
    name = mod.constant_path.name.to_s
    model = Schema.build(mod, result.comments)
    defs = (mod.body&.body || []).grep(Prism::DefNode).map do |node|
      Code.function(node.name.to_s, model.functions.fetch(node.name.to_s), node, model)
    end
    blocks = Schema.declarations(model) + defs
    lean = ["-- Generated by bin/translate from #{path}. Do not edit.", "namespace #{name}",
            *blocks.flat_map { ["", *_1] }, "", "end #{name}", ""]
    [name, lean.join("\n")]
  end
end
