-- Generated by bin/translate from examples/02_order_flow/order_flow.rb. Do not edit.
namespace OrderFlow

inductive Status
  | placed
  | paid
  | shipped
  | cancelled
  deriving DecidableEq, Repr

structure Order where
  status : Status
  total : Int
  paid : Int
  refunded : Int
  seen : List Int
  deriving DecidableEq, Repr

inductive Event
  | pay (id amount : Int)
  | ship (id : Int)
  | cancel (id : Int)
  | refund (id amount : Int)
  deriving DecidableEq, Repr

def Event.id : Event → Int
  | .pay id _ | .ship id | .cancel id | .refund id _ => id

def start (total : Int) : Except String Order :=
  if ¬ total > 0 then .error "total must be positive" else
  .ok { status := .placed, total, paid := 0, refunded := 0, seen := [] }

def apply (order : Order) (event : Event) : Option Order :=
  match order.status, event with
  | .placed, .pay _ amount =>
    if amount > 0 ∧ order.paid + amount ≤ order.total then
      let paid := order.paid + amount
      some { order with paid, status := if paid = order.total then .paid else .placed }
    else none
  | .paid, .ship _ => some { order with status := .shipped }
  | .placed, .cancel _ | .paid, .cancel _ => some { order with status := .cancelled }
  | .cancelled, .refund _ amount =>
    if amount > 0 ∧ order.refunded + amount ≤ order.paid then
      some { order with refunded := order.refunded + amount }
    else none
  | _, _ => none

def step (order : Order) (event : Event) : Order :=
  if event.id ∈ order.seen then order else
  match apply order event with
  | some nxt => { nxt with seen := order.seen ++ [event.id] }
  | none => order

def run (order : Order) (events : List Event) : Order :=
  events.foldl step order

end OrderFlow
