-- Generated by bin/translate from examples/01_money_split/money_split.rb. Do not edit.
namespace MoneySplit

def remainder_last (total parts : Int) : Except String (List Int) :=
  if ¬ parts > 0 then .error "parts must be positive" else
  if total < 0 then .error "total must not be negative" else
  let base := total / parts
  .ok (List.replicate (parts - 1).toNat base ++ [total - (base * (parts - 1))])

def even (total parts : Int) : Except String (List Int) :=
  if ¬ parts > 0 then .error "parts must be positive" else
  if total < 0 then .error "total must not be negative" else
  let base := total / parts
  let extra := total % parts
  .ok ((List.range parts.toNat).map fun (i : Nat) => if (i : Int) < extra then base + 1 else base)

end MoneySplit
